services:
- type: web
  name: flask
  env: python
  buildCommand: pip install -r requirements.txt
  startCommand: gunicorn app:app
- type: web
  name: second-flask
  env: python
  buildCommand: pip install -r requirements.txt
  startCommand: gunicorn app:app
  