services:
- type: web
  name: flask
  env: python
  buildCommand: pip install -r requirements.txt
  startCommand: gunicorn app:app
  scaling:
    minInstances: 1
    maxInstances: 2
    targetCPUPercent: 40