services:
- type: web
  name: flask
  env: python
  plan: starter plus
  buildCommand: pip install -r requirements.txt
  startCommand: gunicorn app:app
- type: web
  name: second-flask
  env: python
  buildCommand: pip install -r requirements.txt
  startCommand: gunicorn app:app
  envVars:
    - key: FLASK_ADDR
      fromService:
        name: flask
        type: web
        property: host
